Athayog/Athayog

src/app/layout.tsx
src/components/_header/MobileDrawer.tsx
src/components/_header/RenderMenuItems.tsx
src/components/_header/styles/MobileDrawer.tsx
src/slices/PersonalSessionHero/index.tsx
src/styles/global.css

Bugfix | Navbar

---

package-lock.json
package.json
src/components/Stats/index.tsx
src/components/Swiper/HorizontalSwiper.tsx
src/components/Swiper/VerticalSwiper.tsx
src/components/_shared/Banner.tsx
src/components/_shared/ResponsiveImage.tsx
src/components/pages/home/WhyAthayog/WhyAthayog.tsx
src/slices/EventHighlightsGallery/index.tsx
src/slices/GroupClass/index.tsx
src/slices/RightContentLeftSliderVertical/index.tsx
src/slices/VideoTestimonials/index.tsx

- Enabled Basic Transitiosn on Count
- Fixed console warnigns

Feature | GSAP

---

src/app/(mobile-app)/athayog-app/privacy/page.tsx
src/app/(mobile-app)/athayog-app/refund/page.tsx
src/app/(mobile-app)/athayog-app/terms/page.tsx
src/app/account/delete-request/layout.tsx
src/app/account/delete-request/page.tsx
src/store/useFormStore.ts

Feature | Delete Account

---

src/slices/CoursesCta/index.tsx

BugFix | CTA Issues

---

src/components/Stats/index.tsx
src/components/WhyAthayog.tsx
src/slices/AlumniArchive/index.tsx
src/slices/Stats/index.tsx

- Fixed hydration error and swiper buttons

BugFix | Swiper & Hydration Errors

---

src/slices/CareerHero/index.tsx
src/slices/ContactUsForm/index.tsx
src/slices/CoursesCta/index.tsx
src/slices/SimpleInformationBlock/index.tsx
src/slices/YogaTherapyHero/index.tsx

- Udpated content via UI
- Udpated UI Feedback

Enhancement | Content & UI Update

---

src/components/_header/RenderMenuItems.tsx
src/slices/ContactUsHero/index.tsx
src/slices/CoursesCta/index.tsx

- Feedback
- Contact US Image
- Footer

Bugfix | Feedback

---

src/slices/ContactUsHero/index.tsx

Patch | Fixed Height

---

.gitignore
next.config.mjs
package-lock.json
package.json
prismicio-types.d.ts
src/components/_header/styles/Index.tsx
src/constants/navItems.ts
src/lib/helpers.ts
src/slices/AlumniArchive/index.tsx
src/slices/GroupClassPricing/index.tsx
src/slices/OurYogaStory/index.tsx
src/slices/PersonalSessionPricing/index.tsx
src/slices/YogaArambha/index.tsx
src/slices/YogaArambha/mocks.json
src/slices/YogaArambha/model.json
src/slices/YogaTherapyPrice/index.tsx
src/styles/global.css
tsconfig.json
video.d.ts
videos/get-started.mp4.json

Feature | Release

---

src/store/useFormStore.ts

- Form Fixes
- Using Web3 Forms as Backup

BugFixes | Post Release Form

---

src/components/_shared/ResponsiveImage.tsx

- Image will now fit to gallery
- Overflow fix

Patch | Image Fit Multi Gallery

---

src/store/useFormStore.ts

- Missing key updated
- Form is fixed

Patch | Update Acess Key

---

src/store/useFormStore.ts

BugFix | Form Key

---

src/slices/MultiGallerySlider/index.tsx

- Added fix for contain images

Patch | Fixed Images

---

src/app/account/delete-request/page.tsx
src/components/Swiper/HorizontalSwiper.tsx
src/components/forms/AcademyForm.tsx
src/components/forms/EnquiryForm.tsx
src/components/forms/WorkshopForm.tsx
src/slices/Forms/index.tsx
src/slices/MultiGallerySlider/index.tsx
src/store/useFormStore.ts

BugFix | Multi Issue

---

src/store/useFormStore.ts

Patch | Email Enabled

---

src/components/_header/MobileDrawer.tsx

- Fixed Mobile button not working
- Added Auth

BugFix | Mobile

---

src/components/forms/WorkshopForm.tsx

- If no payment link just show message

Patch | Payment Link Workshop

---

src/slices/BulletedContent/index.tsx

- Bulleted list slice updated spacing

Patch | Updated Spacing

---

src/slices/Amenities/index.tsx
src/slices/CoursesCta/index.tsx
src/slices/Eligible/index.tsx
src/slices/GroupClass/index.tsx
src/slices/HeroWithCenterText/index.tsx
src/slices/MultiLeftRightCourses/index.tsx
src/slices/MultiLeftRightInfoSection/index.tsx
src/slices/OurYogaStory/index.tsx
src/slices/SimpleTextBlock/index.tsx
src/slices/VideoTestimonials/index.tsx
src/slices/WhyToChoose/index.tsx
src/slices/WorkshopRow/index.tsx

- Fixed Video Collection
- Various Spacing
- Images

Feedback | Desktop

---

src/slices/WeightLossVideos/index.tsx

Removed Button Conditon

---

prismicio-types.d.ts
src/components/Stats/index.tsx
src/components/_shared/Banner.tsx
src/slices/AboutUsHero/index.tsx
src/slices/AboutUsHero/mocks.json
src/slices/AboutUsHero/model.json
src/slices/CareerHero/index.tsx
src/slices/CareerHero/mocks.json
src/slices/CareerHero/model.json
src/slices/ContactUsHero/index.tsx
src/slices/ContactUsHero/mocks.json
src/slices/ContactUsHero/model.json
src/slices/ContentWithImage/index.tsx
src/slices/CoursesHero/index.tsx
src/slices/CoursesHero/mocks.json
src/slices/CoursesHero/model.json
src/slices/CoursesList/index.tsx
src/slices/GroupClassHero/index.tsx
src/slices/GroupClassHero/mocks.json
src/slices/GroupClassHero/model.json
src/slices/HeroWithCenterText/index.tsx
src/slices/HeroWithCenterText/mocks.json
src/slices/HeroWithCenterText/model.json
src/slices/MultiLeftRightCourses/index.tsx
src/slices/PersonalSessionHero/index.tsx
src/slices/PersonalSessionPricing/index.tsx
src/slices/WhyToChoose/index.tsx
src/slices/YogaTherapyHero/index.tsx
src/slices/YogaTherapyHero/mocks.json
src/slices/YogaTherapyHero/model.json

- Revision for mobile
- Added Mobile Changes
- Added Mobile Background

Review  | Mobile

---

src/components/WhyAthayog.tsx
src/slices/GroupSchedule/index.tsx

- December Schedule Added
- Manual Changes Done and Added 11-12

Update | Schedule December

---

src/components/WhyAthayog.tsx
src/slices/RightContentLeftSliderVertical/index.tsx

Enhancement | Swiper Vertical Scroll

---

src/components/WhyAthayog.tsx
src/slices/RightContentLeftSliderVertical/index.tsx

BugFix | Vertical Slider

---

src/app/robots.ts
src/app/sitemap.ts

- Added Dynamic Sitemap
- Added Dynamic Robots

Feature | Sitemap & Robots

---

src/components/PostCard.tsx

Patch | Made Blogs Title Visible On Mobile

---

src/app/layout.tsx

Enhancement | Added Google Site Verify

---

src/slices/GroupSchedule/index.tsx

Update | Schedule 2025

---

src/slices/GroupSchedule/index.tsx

Update | Schedule March 25

---

package-lock.json
package.json
prismicio-types.d.ts
src/app/api/create-order/route.ts
src/slices/GroupClassPricing/index.tsx
src/slices/GroupClassPricing/mocks.json
src/slices/GroupClassPricing/model.json
src/slices/PersonalSessionPricing/mocks.json
src/slices/PersonalSessionPricing/model.json
src/slices/YogaTherapyPrice/index.tsx
src/slices/YogaTherapyPrice/mocks.json
src/slices/YogaTherapyPrice/model.json

Feature | GST Pricing

---

src/slices/GroupSchedule/index.tsx

Update | Schedule May

---

src/app/(protected)/scanner/scanner.tsx
src/app/(protected)/scanner/styles/Scanner.tsx
src/app/api/yoga-day/route.ts
src/app/layout.tsx
src/components/WhatsApp.tsx
src/components/_footer/FooterComponent.tsx
src/components/_header/index.tsx

Feature | Scan Counter & Redesign

---

src/app/(protected)/scanner/scanner.tsx

HotFix | Scanner Access
